version: '3.8'

services:
  specifix_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: specifix_api
    ports:
      - "8088:808"
      - "8022:22"
    volumes:
      - "./uploads:/workspace/uploads/"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
